apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: bookstore-platform
  labels:
    app: backend
    tier: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
        tier: app
    spec:
      containers:
      # Main app (no probes, no port exposure)
      - name: backend-app
        image: omaradel2001/bookstore-backend:v1.3
        env:
        - name: DB_HOST
          value: "mysql"
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_DATABASE
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: mysql-config
              key: MYSQL_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: MYSQL_PASSWORD
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "300m"

      # Proxy sidecar (handles probes and traffic)
      - name: nginx-proxy
        image: nginx:alpine
        ports:
        - containerPort: 3000
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 20
          periodSeconds: 5
      volumes:
      - name: nginx-conf
        configMap:
          name: backend-nginx-proxy
