apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: bookstore-platform
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: selconyt/bookstore-frontend:v1.3
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: bookstore-platform
spec:
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 8080

